input_validator_flags: ''
output_validator_flags: ''
static_validator_flags: '' #TODO for testing
on_reject: break

grading: default
grader_flags: ''

accept_score: 1.0
reject_score: 0.0
range: '-inf +inf'

static_validation: 'false' #TODO for testing